updating app title and readme
flutter-dev-malaysia/flutter-malaysia-app pull request #1
Opened 2020-02-08 08:03 UTC by lion4h

2020-02-08 09:07 UTC, zulfahmi93 commented
Thanks @lion4h for the PR. Please move the `android/app/src/main/kotlin/flutterdev/my/flutter_my_app/MainActivity.kt` file to `android/app/src/main/kotlin/my/flutter/meeting/MainActivity.kt` because you updated the package. Once it's done, I'll merge this PR.

2020-02-08 09:15 UTC, zulfahmi93 requested changes
Thanks @lion4h for the PR. Please move the `android/app/src/main/kotlin/flutterdev/my/flutter_my_app/MainActivity.kt` file to `android/app/src/main/kotlin/my/flutter/meeting/MainActivity.kt` because you updated the package. Once it's done, I'll merge this PR.

2020-02-08 10:00 UTC, lion4h commented
Kotlin support should be removed thought, not needed.

2020-02-09 03:44 UTC, zulfahmi93 approved these changes

2020-02-09 03:45 UTC, merged